import './globals.css'

import {Poppins} from 'next/font/google'

import Header from "@/components/header"
import Providers from "@/components/providers";

const poppins = Poppins({subsets: ['latin'], weight: ["300", "400", "500", "600", "700", "800"]})

export const metadata = {
    title: 'Next Blog',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={poppins.className}>
        <Providers>
            <Header/>
            {children}

        </Providers>
        </body>
        </html>
    )
}
